name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch>=1.10.0
      - torchvision>=0.11.0
      - pytorch-lightning==1.5.5 # For compatibility with mlflow
      - torchmetrics>=0.6.0
      - hydra-core==1.1.0
      - hydra-colorlog==1.1.0
      - hydra-optuna-sweeper==1.1.0
      - mlflow
      - wandb
      - python-dotenv
      - rich
      - pytest
      - sh
      - boto3
      - setuptools==59.5.0 # For compatibility with PL
      - dvc[s3]
