name: Build images

on:
  #schedule:
  #- cron: "0 10 * * *" # everyday at 10am
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  base:
    secrets:
      GITLAB_REGISTRY_USERNAME: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      GITLAB_REGISTRY_TOKEN: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: base
      context: base
      test: true
      push: true
      base_image: debian:stable-slim
      base_image_gpu: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04
  python-minimal:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    secrets:
      GITLAB_REGISTRY_USERNAME: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      GITLAB_REGISTRY_TOKEN: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
    needs: [base]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-minimal
      context: python-minimal
      test: false
      push: true
      base_image: registry.gitlab.inria.fr/sed-paris/mpp/containers/mpp-base:latest
      base_image_gpu: registry.gitlab.inria.fr/sed-paris/mpp/containers/mpp-base:latest-gpu
  python-datascience:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    secrets:
      GITLAB_REGISTRY_USERNAME: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      GITLAB_REGISTRY_TOKEN: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-datascience
      context: python-datascience
      test: false
      push: true
      base_image: registry.gitlab.inria.fr/sed-paris/mpp/containers/mpp-python-minimal:latest
      base_image_gpu: registry.gitlab.inria.fr/sed-paris/mpp/containers/mpp-python-minimal:latest-gpu
